---
title: "Microbiome and Community analysis"
author: "Kendra Maas"
date: "December 15, 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# UConn CGI Microbial Ecology Workshop 

Microbes control the world! And with advances in molecular techniques, esp. DNA sequencing, we can explore the microbial side with ever increasing depth and breadth. But the data generated by sequencing the microbial world is bigish and weird. Most bioinformatic tools don't handle the taxonomic markers that we like to sequence very well. There are a few specialized programs for processing phylogenetic marker sequences, my preferred program is mothur <http://www.mothur.org/wiki/MiSeq_SOP>. We will use mothur generated OTU table (species by sample matrix), then take those into R to explore the data and learn how to make publication quality figures. 

In class discussions and commands will be posted in an etherpad <https://etherpad.mit.edu/p/20251215MEworkshop>



[Kendra's bash script for downloading data from Basespace](https://github.com/krmaas/bioinformatics/blob/master/bscli.bash)

[Kendra's mothur cheatsheet](https://krmaas.github.io/20251215MEworkshop/mothur.cheatsheet.html)


<!--

[Kendra's mothur Fungal script](https://github.com/krmaas/bioinformatics/blob/master/mothur.fungal.batch)

Theta YC paper <https://www.tandfonline.com/doi/full/10.1080/STA-200066418>

[How to make Krona plot](https://github.com/accaldwell/mothur_krona)

[bioblitz environmental data](https://krmaas.github.io/20230814MEworkshop/may18ws.env.txt)

[bioblitz sample names](https://krmaas.github.io/20230814MEworkshop/may18ws.sample.txt)

[Read mothur files into R]()

[Kendra's starting R script](https://github.com/krmaas/bioinformatics/blob/master/GENERICdata.exploration.Rmd)

[stacked bar graph script](https://github.com/krmaas/20191217MARSme/blob/master/stackBar.R)

[Kendra's R script from the workshop]

-->

Basic Schedule. We will roughly follow this, but the exact amount of time we spend on each topic will be adjusted depending on the class.


Day|Session|Topic
------|-------|--------
Day 1|Morning|[Introduction to communities](https://krmaas.github.io/20251215MEworkshop/intro.communities.html)
.|.|[Overview of wetlab](https://krmaas.github.io/20251215MEworkshop/introWetLab.html) 
.|.|[Potential wetlab errors](https://krmaas.github.io/20251215MEworkshop/wetLabErrors.html)
.|Afternoon| [Introduction to Basespace and Command Line](https://krmaas.github.io/20251215MEworkshop/intro.seq.analysis.html)
.|.|Begin mothur processing
.|.|Sequencing quality control
Day 2|Morning|Continue mothur processing
.|.|Chimera checking
.|.|Taxonomic assignment
.|Afternoon|OTU clustering
.|.|Calculate alpha and beta diversity
.|.|Scripts for other taxonomic markers
Day 3|Morning|Reproducible Research
.|.|Introduction to R ggplot
.|Afternoon|Importing data into R
.|.|Import mothur into R
.|.|Subsetting, joining, data management
Day 4|Morning|Ecological statistics
.|Afternoon|Hypothesis testing & Selecting indicator OTUs
